#!/bin/bash

#---
## @Synopsis Migrate php sessions from disk to redis using mass insertion
## @Copyright Copyleft 2013 renasboy <renasboy@gmail.com>
## @License GPL v3
## 
## Reads session stored in $php_session_dir and transfer the contents to
## redis database using redis-cli pipe mode and redis mass insertion protocol.
## Sessions are stored with the $php_session_prefix as prefix.
## This script calls itself providing the session file location
##
##
#---

# declaring the php session directory location
# basically this is your session.save_path
php_session_dir=/var/lib/php5

# this is the php session prefix inside redis
php_session_prefix=PHPREDIS_SESSION

function echoRedisProtocolInsertSession() {
    local sessionFileName="$1"

    if test -n "$sessionFileName" -a -f "$sessionFileName"; then
        # generate the session id cause we need to get the length of it
        session_id=$php_session_prefix:$(basename ${1/sess_/})
        echo -n -e "*3\r\n"               # *<args>
        echo -n -e "\$3\r\n"              # $<len arg0>
        echo -n -e "SET\r\n"              # <arg0> (command)
        echo -n -e "\$${#session_id}\r\n" # $<len arg1>
        echo -n -e "$session_id\r\n"      # <arg1=key>
        echo -n -e "\$$(echo -n -e "$(escapeValue "$sessionFileName")"| wc -c)\r\n"     # $<len arg2>
        echo -n -e "$(escapeValue "$sessionFileName")\r\n"                              # <arg2=value>
    fi
}
function escapeValue() {
    local sessionFileName="$1"

    echo -n -e "$(sed 's/\\/\\\\/g' $sessionFileName | sed 's/\x00/\\\\x00/g')"
}

export -f echoRedisProtocolInsertSession
export -f escapeValue
export php_session_prefix

# trap method to cleanup on exit
trap cleanexit EXIT

cleanexit () {
    if test -d "$tmp_dir"; then
        rm -rf "$tmp_dir"
    fi
}

# create temp dir where data is stored
tmp_dir=`mktemp -d`

# first cleanup all zero byte sessions
echo "removing empty session files"
find $php_session_dir -type f -size 0 -name "sess_*" -exec rm -f {} \; 2>/dev/null

echo "generating the data file with redis protocol for mass insertion"
#http://redis.io/topics/mass-insert
find $php_session_dir -type f -name "sess_*" -exec bash -c 'echoRedisProtocolInsertSession "$0"' {} \; > $tmp_dir/data.txt 2>/dev/null

echo "loading data into redis using the redis-cli pipe mode"
cat $tmp_dir/data.txt | redis-cli --pipe

# exit gracefully
exit 0
